apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-store
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sample-store
  template:
    metadata:
      labels:
        app: sample-store
    spec:
      containers:
        - image: ghcr.io/miladbeigi/sample-store-app:main
          name: sample-store
          ports:
            - containerPort: 80
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: sample-store-key
                  key: SECRET_KEY_BASE
