metadata:
  name: sample-store-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: sample-store
    repoURL: ghcr.io/miladbeigi/sample-store-app
    targetRevision: v1.0.7
